package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'Project_DslParametersWithSync_MavenProject_SimpleEcho'
in the project with id = 'MavenProject', and delete the patch script.
*/
create(RelativeId("MavenProject"), BuildType({
    id = AbsoluteId("Project_DslParametersWithSync_MavenProject_SimpleEcho")
    name = "MavenEchoBuild"

    steps {
        script {
            id = "RUNNER_1"
            scriptContent = """
                echo "Special Russial Symbol: символы"
                echo "Property from local file: value"
                echo "Optional Parameter: DEFAULT"
            """.trimIndent()
        }
    }
}))

