package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'MavenProject_RunTests'
in the project with absolute id = 'ProjectName_DslParametersWithSync_MavenProject', and delete the patch script.
*/
create(AbsoluteId("ProjectName_DslParametersWithSync_MavenProject"), BuildType({
    id("MavenProject_RunTests")
    name = "MavenBuild"

    vcs {
        root(RelativeId("MavenProject_ProjectRoot"))
    }

    steps {
        maven {
            id = "RUNNER_1"
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }
}))

