package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a root project
in the project with absolute id = DslContext.parentProjectId, and delete the patch script.
*/
create(DslContext.parentProjectId, Project({
    defaultTemplate = AbsoluteId("Project_DslParametersWithSync_DefaultTemplateWithParameter")
}))

