package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with absolute id = 'Project_DslParametersWithSync_MavenProject_ProjectRoot'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id = AbsoluteId("Project_DslParametersWithSync_MavenProject_ProjectRoot")
    name = "MavenVCS"
    url = "https://github.com/burnasheva/dsl-non-portable-simple"
    branchSpec = "+:refs/heads/*"
    authMethod = password {
        userName = "burnasheva"
        password = "credentialsJSON:65bd2531-08d0-423a-a578-f853db5b788f"
    }
}))

